---
- hosts: webserver
  become: yes
  become_method: sudo
  tasks:
    - name: install apache web server
      package:
        name: httpd
        state: latest
    
    - name: copy index webpage
      copy:
        src: './files/index.html'
        dst: '/var/www/html/index.html'

    - name: start and enable apache web server
      service:
        name: httpd
        state: started
        enabled: true
