---
- hosts: webserver
  tasks:
    - name: install apache web server
      package:
        name: httpd
        state: latest
    
    - name: copy index webpage
      copy:
        src: './files/index.html'
        dest: '/var/www/html/index.html'

    - name: start and enable apache web server
      service:
        name: httpd
        state: started
        enabled: true
